PLAYER_HEAD_ID = 0
PLAYER_SHIRT_ID = 0
PLAYER_PANTS_ID = 0
PLAYER_EYEBROWS_ID = 0
PLAYER_EYES_ID = 0
PLAYER_ARMS_ID = 0
PLAYER_FEET_ID = 0
PLAYER_HAIR_COLOR_ID = 0
PLAYER_HAIR_STYLE_ID = 1
PLAYER_POSITION = (0, 0)


