import globalVars.PathConstants as PATH_CONSTANTS
import pygame

CURRENT_AREA_INDEX = 0
CURRENT_MAP_INDEX = 0
CURRENT_PLAYER_POS = (0, 0)
CURRENT_SCENE_TYPE = PATH_CONSTANTS.AREA

PLAYER_HEAD_ID = 0
PLAYER_BODY_ID = 0
PLAYER_POSITION = (0, 0)
