import globalVars.PathConstants as PATH_CONSTANTS
import pygame

#### SAVED AREA ####
CURRENT_AREA_INDEX = 0
CURRENT_MAP_INDEX = 0
CURRENT_PLAYER_POS = (0, 0)
CURRENT_SCENE_TYPE = PATH_CONSTANTS.AREA

#### SAVED PLAYER OUTFIT ####
PLAYER_HEAD_ID = 0
PLAYER_SHIRT_ID = 0
PLAYER_PANTS_ID = 0
PLAYER_EYEBROWS_ID = 0
PLAYER_EYES_ID = 0
PLAYER_ARMS_ID = 0
PLAYER_SHOES_ID = 0
PLAYER_HAIR_ID = 0

PLAYER_POSITION = (0, 0)

#### CONTROLS ####
PLAYER_WALK_LEFT_KEY_ID = pygame.K_a
PLAYER_WALK_RIGHT_KEY_ID = pygame.K_d
PLAYER_WALK_DOWN_KEY_ID = pygame.K_s
PLAYER_WALK_UP_KEY_ID = pygame.K_w
PLAYER_RUN_KEY_ID = pygame.K_LSHIFT
