import globalVars.PathConstants as PATH_CONSTANTS
import pygame
import Font.FontPaths as FONT_PATHS

'''
The following file contains defaults for saved data. These variables are updated on game initialization.

'''
#### SAVED AREA ####
CURRENT_AREA_INDEX = 0
CURRENT_MAP_INDEX = 0
CURRENT_PLAYER_POS = (0, 0)
CURRENT_SCENE_TYPE = PATH_CONSTANTS.AREA

#### SAVED PLAYER OUTFIT ####
PLAYER_HEAD_ID = 0
PLAYER_SHIRT_ID = 0
PLAYER_PANTS_ID = 0
PLAYER_EYEBROWS_ID = 0
PLAYER_EYES_ID = 0
PLAYER_ARMS_ID = 0
PLAYER_FEET_ID = 0
PLAYER_HAIR_COLOR_ID = 0
PLAYER_HAIR_STYLE_ID = 0
PLAYER_POSITION = (0, 0)

#### CONTROLS ####

##BATTLE##
BATTLE_TIMING_BUTTON = pygame.K_SPACE

##PLAYER##
PLAYER_WALK_LEFT_KEY_ID = pygame.K_a
PLAYER_WALK_RIGHT_KEY_ID = pygame.K_d
PLAYER_WALK_DOWN_KEY_ID = pygame.K_s
PLAYER_WALK_UP_KEY_ID = pygame.K_w
PLAYER_RUN_KEY_ID = pygame.K_LSHIFT
PLAYER_PAUSE_KEY_ID = pygame.K_x
PLAYER_SELECTION_KEY_ID = pygame.K_RETURN
PLAYER_SELECTION_KEYS = pygame.K_RETURN, pygame.K_SPACE

##UI##
UI_MOVE_LEFT = pygame.K_LEFT, pygame.K_a
UI_MOVE_RIGHT = pygame.K_RIGHT, pygame.K_d
UI_MOVE_DOWN = pygame.K_DOWN, pygame.K_s
UI_MOVE_UP = pygame.K_UP, pygame.K_w
UI_SELECT = pygame.K_RETURN, pygame.K_SPACE

##SETTINGS##
SCREEN_SIZE = "FULLSCREEN"
FONT = "GOHU"
FONT_PATH = FONT_PATHS.GOHU
