'''
MOVE FORMAT:
MOVE_NAME = {
    NAME : "MOVE_NAME",
    TYPE : MoveTypes.MOVE_TYPE,
    DMG : DMG_VAL,
    LUCK : LUCK_VAL

    
}
'''
NAME = 'NAME'
DMG = 'DAMAGE'
LUCK = 'LUCK'
TYPE = 'TYPE'
NONE = "NONE"

class MoveTypes:
    STATUS_EFFECT = "STATUS_EFFECT"
    MELEE = "MELEE"
    RANGED = "RANGED"

PUNCH = {
        NAME: "PUNCH",
        TYPE: MoveTypes.MELEE,
        DMG: 5,
        LUCK: 10,
}
HEADBUTT = {
        NAME: "HEADBUTT",
        TYPE: MoveTypes.MELEE,
        DMG: 7,
        LUCK: 0,
}
KICK = {
        NAME: 'KICK',
        TYPE: MoveTypes.MELEE,
        DMG: 7,
        LUCK: 5,
}

MOVE_LIST = [PUNCH, HEADBUTT, KICK]
MOVE_NAMES = [move[NAME] for move in MOVE_LIST]
'''
FORMAT OF ANIMATION_DATA DICT (Assuming there are K moves in this game:
ANIM_DATA {
    {MOVE_NAME0}: [MOVE_0_NUM_FRAMES, MOVE_0.WIND_UP_FRAME_IDX, MOVE_0.FULLY_EXTENDED_FRAME_IDX]
    {MOVE_NAME1}: [MOVE_1_NUM_FRAMES, MOVE_1.WIND_UP_FRAME_IDX, MOVE_1.FULLY_EXTENDED_FRAME_IDX]
    {MOVE_NAME[K-1]}: [MOVE_K-1_NUM_FRAMES, MOVE_K-1.WIND_UP_FRAME_IDX, MOVE_K-1.FULLY_EXTENDED_FRAME_IDX]
}
    # WHERE IDX STARTS AT 0 AND MUST BE IN BETWEEN
    # 0 AND N-1 ASSUMING AN N FRAME ANIMATION
'''
FRAME_SIZE_IDX = 0
WIND_UP_FRAME_IDX = 1
FULL_EXTENSION_FRAME_IDX = 2

ANIMATION_DATA = {
        PUNCH[NAME] : [8, 2, 5]
}
